databases:
  - name: insta
    databaseName: insta
    user: insta

services:
  - type: web
    name: insta
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: insta
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false